-- Скрипт создания ролей, пользователей и основных привилегий (запускать в sqlplus от SYS/администратора)

-- Удаление 
BEGIN EXECUTE IMMEDIATE 'DROP USER COSM_ADMIN CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP USER COSM_USER CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP ROLE COSM_ROLE_ADMIN'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP ROLE COSM_ROLE_USER'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Создание ролей
BEGIN
  EXECUTE IMMEDIATE 'ALTER SESSION SET "_ORACLE_SCRIPT"=true';
  EXECUTE IMMEDIATE 'CREATE ROLE COSM_ROLE_ADMIN';
  EXECUTE IMMEDIATE 'CREATE ROLE COSM_ROLE_USER';
  DBMS_OUTPUT.PUT_LINE('Роли созданы');
EXCEPTION WHEN OTHERS THEN 
  DBMS_OUTPUT.PUT_LINE('Ошибка создания ролей: ' || SQLERRM);
END;
/

-- Создание пользователей
BEGIN
  EXECUTE IMMEDIATE 'CREATE USER COSM_ADMIN IDENTIFIED BY "1111"
    DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED ON USERS';
    
  EXECUTE IMMEDIATE 'CREATE USER COSM_USER IDENTIFIED BY "1111"
    DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED ON USERS';
  DBMS_OUTPUT.PUT_LINE('Пользователи созданы');
EXCEPTION WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('Ошибка создания пользователей: ' || SQLERRM);
END;
/

-- Создание директорий для файлов 
BEGIN
  EXECUTE IMMEDIATE 'CREATE OR REPLACE DIRECTORY COSM_JSON_DIR AS ''D:\Orance\json_data''';
  EXECUTE IMMEDIATE 'CREATE OR REPLACE DIRECTORY COSM_IMAGES_DIR AS ''D:\Orance\images''';
  DBMS_OUTPUT.PUT_LINE('Директории созданы');
EXCEPTION WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('Ошибка создания директорий: ' || SQLERRM);
  DBMS_OUTPUT.PUT_LINE('ВАЖНО: Создайте директории вручную или запустите от имени SYS');
END;
/

-- Права на подключение
BEGIN
  EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO COSM_ADMIN, COSM_USER';
  DBMS_OUTPUT.PUT_LINE('Права на подключение предоставлены');
EXCEPTION WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('Ошибка предоставления прав на подключение: ' || SQLERRM);
END;
/

-- Права администратора на создание объектов схемы
BEGIN
  EXECUTE IMMEDIATE 'GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE TRIGGER, CREATE PROCEDURE, CREATE TYPE, CREATE SYNONYM TO COSM_ADMIN';
  DBMS_OUTPUT.PUT_LINE('Права администратора предоставлены');
EXCEPTION WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('Ошибка предоставления прав администратора: ' || SQLERRM);
END;
/

-- Предоставление ролей пользователям
BEGIN
  EXECUTE IMMEDIATE 'GRANT COSM_ROLE_ADMIN TO COSM_ADMIN';
  EXECUTE IMMEDIATE 'GRANT COSM_ROLE_USER TO COSM_USER';
  DBMS_OUTPUT.PUT_LINE('Роли назначены пользователям');
EXCEPTION WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('Ошибка назначения ролей: ' || SQLERRM);
END;
/

-- Доступ к каталогу
BEGIN
  EXECUTE IMMEDIATE 'GRANT READ, WRITE ON DIRECTORY COSM_JSON_DIR TO COSM_ADMIN';
  EXECUTE IMMEDIATE 'GRANT READ ON DIRECTORY COSM_JSON_DIR TO COSM_USER';
  EXECUTE IMMEDIATE 'GRANT READ ON DIRECTORY COSM_IMAGES_DIR TO COSM_ADMIN';
  EXECUTE IMMEDIATE 'GRANT READ ON DIRECTORY COSM_IMAGES_DIR TO COSM_USER';
  DBMS_OUTPUT.PUT_LINE('Права на директории предоставлены');
EXCEPTION WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('Ошибка предоставления прав на директории: ' || SQLERRM);
END;
/

-- Базовые права для ролей 
BEGIN
  EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO COSM_ROLE_USER';
  
  DBMS_OUTPUT.PUT_LINE('Базовые права для ролей предоставлены');
EXCEPTION WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('Ошибка предоставления базовых прав: ' || SQLERRM);
END;
/


BEGIN
  -- Права на таблицы
  EXECUTE IMMEDIATE 'GRANT SELECT ON categories TO COSM_USER';
  EXECUTE IMMEDIATE 'GRANT SELECT ON companies TO COSM_USER';
  EXECUTE IMMEDIATE 'GRANT SELECT ON products TO COSM_USER';
  EXECUTE IMMEDIATE 'GRANT SELECT ON inventory TO COSM_USER';
  EXECUTE IMMEDIATE 'GRANT SELECT ON customers TO COSM_USER';
  EXECUTE IMMEDIATE 'GRANT SELECT ON orders TO COSM_USER';
  EXECUTE IMMEDIATE 'GRANT SELECT ON order_items TO COSM_USER';
  EXECUTE IMMEDIATE 'GRANT SELECT ON payments TO COSM_USER';
  DBMS_OUTPUT.PUT_LINE('Права на таблицы предоставлены');

  -- Права на пакеты
  EXECUTE IMMEDIATE 'GRANT EXECUTE ON pkg_shop TO COSM_USER';
  EXECUTE IMMEDIATE 'GRANT EXECUTE ON pkg_analytics TO COSM_USER';
  -- Примечание: права на pkg_admin_runner предоставляются в самом файле pkg_admin_runner.sql после его создания
  DBMS_OUTPUT.PUT_LINE('Права на пакеты предоставлены');

  -- Права на представления
  EXECUTE IMMEDIATE 'GRANT SELECT ON v_product_overview TO COSM_USER';
  EXECUTE IMMEDIATE 'GRANT SELECT ON v_popular_products TO COSM_USER';
  DBMS_OUTPUT.PUT_LINE('Права на представления предоставлены');
  
EXCEPTION WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('Ошибка предоставления прав: ' || SQLERRM);
END;
/